// Auto-generated comprehensive emoji catalog
const EMOJI_CATALOG = [
  {e:'😀', name:'Grinning', cat:'faces', price:25, rarity:'rare'},
  {e:'😃', name:'Big Smile', cat:'faces', price:10, rarity:'common'},
  {e:'😄', name:'Cheerful', cat:'faces', price:10, rarity:'common'},
  {e:'😁', name:'Beaming', cat:'faces', price:10, rarity:'common'},
  {e:'😆', name:'Laughing', cat:'faces', price:10, rarity:'common'},
  {e:'😅', name:'Sweat Smile', cat:'faces', price:10, rarity:'common'},
  {e:'🤣', name:'ROFL', cat:'faces', price:10, rarity:'common'},
  {e:'😂', name:'Joy Tears', cat:'faces', price:10, rarity:'common'},
  {e:'🙂', name:'Slight Smile', cat:'faces', price:10, rarity:'common'},
  {e:'🙃', name:'Upside Down', cat:'faces', price:10, rarity:'common'},
  {e:'😉', name:'Wink', cat:'faces', price:25, rarity:'rare'},
  {e:'😊', name:'Blush', cat:'faces', price:60, rarity:'epic'},
  {e:'😇', name:'Innocent', cat:'faces', price:10, rarity:'common'},
  {e:'🥰', name:'Lovestruck', cat:'faces', price:10, rarity:'common'},
  {e:'😍', name:'Heart Eyes', cat:'faces', price:10, rarity:'common'},
  {e:'🤩', name:'Star Struck', cat:'faces', price:25, rarity:'rare'},
  {e:'😘', name:'Kiss Face', cat:'faces', price:25, rarity:'rare'},
  {e:'😗', name:'Kiss', cat:'faces', price:10, rarity:'common'},
  {e:'☺️', name:'Relaxed', cat:'faces', price:25, rarity:'rare'},
  {e:'😚', name:'Closed Kiss', cat:'faces', price:10, rarity:'common'},
  {e:'😙', name:'Smile Kiss', cat:'faces', price:10, rarity:'common'},
  {e:'🥲', name:'Smiling Tear', cat:'faces', price:60, rarity:'epic'},
  {e:'😋', name:'Yum', cat:'faces', price:10, rarity:'common'},
  {e:'😛', name:'Tongue', cat:'faces', price:10, rarity:'common'},
  {e:'😜', name:'Wink Tongue', cat:'faces', price:10, rarity:'common'},
  {e:'🤪', name:'Zany', cat:'faces', price:10, rarity:'common'},
  {e:'😝', name:'Squint Tongue', cat:'faces', price:25, rarity:'rare'},
  {e:'🤑', name:'Money Mouth', cat:'faces', price:10, rarity:'common'},
  {e:'🤗', name:'Hugging', cat:'faces', price:10, rarity:'common'},
  {e:'🤭', name:'Hand Over Mouth', cat:'faces', price:10, rarity:'common'},
  {e:'🫢', name:'Gasp', cat:'faces', price:25, rarity:'rare'},
  {e:'🫣', name:'Peeking', cat:'faces', price:60, rarity:'epic'},
  {e:'🤫', name:'Shushing', cat:'faces', price:25, rarity:'rare'},
  {e:'🤔', name:'Thinking', cat:'faces', price:25, rarity:'rare'},
  {e:'🫡', name:'Saluting', cat:'faces', price:10, rarity:'common'},
  {e:'🤐', name:'Zipper', cat:'faces', price:60, rarity:'epic'},
  {e:'🤨', name:'Raised Brow', cat:'faces', price:25, rarity:'rare'},
  {e:'😐', name:'Neutral', cat:'faces', price:10, rarity:'common'},
  {e:'😑', name:'Expressionless', cat:'faces', price:60, rarity:'epic'},
  {e:'😶', name:'No Mouth', cat:'faces', price:10, rarity:'common'},
  {e:'🫥', name:'Dotted Line', cat:'faces', price:10, rarity:'common'},
  {e:'😏', name:'Smirk', cat:'faces', price:60, rarity:'epic'},
  {e:'😒', name:'Unamused', cat:'faces', price:25, rarity:'rare'},
  {e:'🙄', name:'Eye Roll', cat:'faces', price:10, rarity:'common'},
  {e:'😬', name:'Grimace', cat:'faces', price:10, rarity:'common'},
  {e:'🤥', name:'Lying', cat:'faces', price:10, rarity:'common'},
  {e:'😌', name:'Relieved', cat:'faces', price:10, rarity:'common'},
  {e:'😔', name:'Pensive', cat:'faces', price:25, rarity:'rare'},
  {e:'😪', name:'Sleepy', cat:'faces', price:10, rarity:'common'},
  {e:'🤤', name:'Drooling', cat:'faces', price:25, rarity:'rare'},
  {e:'😴', name:'Sleeping', cat:'faces', price:25, rarity:'rare'},
  {e:'😷', name:'Mask', cat:'faces', price:10, rarity:'common'},
  {e:'🤒', name:'Thermometer', cat:'faces', price:10, rarity:'common'},
  {e:'🤕', name:'Bandaged', cat:'faces', price:10, rarity:'common'},
  {e:'🤢', name:'Nauseated', cat:'faces', price:25, rarity:'rare'},
  {e:'🤮', name:'Vomiting', cat:'faces', price:10, rarity:'common'},
  {e:'🤧', name:'Sneeze', cat:'faces', price:10, rarity:'common'},
  {e:'🥵', name:'Hot', cat:'faces', price:60, rarity:'epic'},
  {e:'🥶', name:'Cold', cat:'faces', price:150, rarity:'legendary'},
  {e:'🥴', name:'Woozy', cat:'faces', price:10, rarity:'common'},
  {e:'😵', name:'Knocked Out', cat:'faces', price:25, rarity:'rare'},
  {e:'😵‍💫', name:'Spiral Eyes', cat:'faces', price:10, rarity:'common'},
  {e:'🤯', name:'Mind Blown', cat:'faces', price:10, rarity:'common'},
  {e:'🤠', name:'Cowboy', cat:'faces', price:25, rarity:'rare'},
  {e:'🥳', name:'Party', cat:'faces', price:150, rarity:'legendary'},
  {e:'🥸', name:'Disguised', cat:'faces', price:25, rarity:'rare'},
  {e:'😎', name:'Cool Shades', cat:'faces', price:10, rarity:'common'},
  {e:'🤓', name:'Nerd', cat:'faces', price:10, rarity:'common'},
  {e:'🧐', name:'Monocle', cat:'faces', price:10, rarity:'common'},
  {e:'😕', name:'Confused', cat:'faces', price:10, rarity:'common'},
  {e:'🫤', name:'Diagonal', cat:'faces', price:25, rarity:'rare'},
  {e:'😟', name:'Worried', cat:'faces', price:10, rarity:'common'},
  {e:'🙁', name:'Frowning', cat:'faces', price:10, rarity:'common'},
  {e:'☹️', name:'Frown', cat:'faces', price:60, rarity:'epic'},
  {e:'😮', name:'Open Mouth', cat:'faces', price:10, rarity:'common'},
  {e:'😯', name:'Hushed', cat:'faces', price:10, rarity:'common'},
  {e:'😲', name:'Astonished', cat:'faces', price:25, rarity:'rare'},
  {e:'😳', name:'Flushed', cat:'faces', price:10, rarity:'common'},
  {e:'🥺', name:'Pleading', cat:'faces', price:10, rarity:'common'},
  {e:'🥹', name:'Holding Back', cat:'faces', price:60, rarity:'epic'},
  {e:'😦', name:'Frowning Open', cat:'faces', price:10, rarity:'common'},
  {e:'😧', name:'Anguished', cat:'faces', price:10, rarity:'common'},
  {e:'😨', name:'Fearful', cat:'faces', price:25, rarity:'rare'},
  {e:'😰', name:'Anxious', cat:'faces', price:25, rarity:'rare'},
  {e:'😥', name:'Sad Sweat', cat:'faces', price:150, rarity:'legendary'},
  {e:'😢', name:'Crying', cat:'faces', price:10, rarity:'common'},
  {e:'😭', name:'Sobbing', cat:'faces', price:10, rarity:'common'},
  {e:'😱', name:'Screaming', cat:'faces', price:60, rarity:'epic'},
  {e:'😖', name:'Confounded', cat:'faces', price:10, rarity:'common'},
  {e:'😣', name:'Persevering', cat:'faces', price:25, rarity:'rare'},
  {e:'😞', name:'Disappointed', cat:'faces', price:10, rarity:'common'},
  {e:'😓', name:'Downcast', cat:'faces', price:25, rarity:'rare'},
  {e:'😩', name:'Weary', cat:'faces', price:25, rarity:'rare'},
  {e:'😫', name:'Tired', cat:'faces', price:150, rarity:'legendary'},
  {e:'🥱', name:'Yawn', cat:'faces', price:60, rarity:'epic'},
  {e:'😤', name:'Triumph', cat:'faces', price:60, rarity:'epic'},
  {e:'😡', name:'Pouting', cat:'faces', price:10, rarity:'common'},
  {e:'😠', name:'Angry', cat:'faces', price:25, rarity:'rare'},
  {e:'🤬', name:'Cursing', cat:'faces', price:10, rarity:'common'},
  {e:'😈', name:'Devil', cat:'faces', price:10, rarity:'common'},
  {e:'👿', name:'Imp', cat:'faces', price:25, rarity:'rare'},
  {e:'💀', name:'Skull', cat:'faces', price:60, rarity:'epic'},
  {e:'☠️', name:'Skull Bones', cat:'faces', price:25, rarity:'rare'},
  {e:'💩', name:'Poop', cat:'faces', price:10, rarity:'common'},
  {e:'🤡', name:'Clown', cat:'faces', price:60, rarity:'epic'},
  {e:'👹', name:'Ogre', cat:'faces', price:10, rarity:'common'},
  {e:'👺', name:'Goblin', cat:'faces', price:10, rarity:'common'},
  {e:'👻', name:'Ghost', cat:'faces', price:150, rarity:'legendary'},
  {e:'👽', name:'Alien', cat:'faces', price:60, rarity:'epic'},
  {e:'👾', name:'Space Invader', cat:'faces', price:10, rarity:'common'},
  {e:'🤖', name:'Robot', cat:'faces', price:25, rarity:'rare'},
  {e:'😺', name:'Cat Smile', cat:'faces', price:10, rarity:'common'},
  {e:'😸', name:'Cat Grin', cat:'faces', price:10, rarity:'common'},
  {e:'😹', name:'Cat Joy', cat:'faces', price:25, rarity:'rare'},
  {e:'😻', name:'Cat Heart', cat:'faces', price:25, rarity:'rare'},
  {e:'😼', name:'Cat Smirk', cat:'faces', price:150, rarity:'legendary'},
  {e:'😽', name:'Cat Kiss', cat:'faces', price:25, rarity:'rare'},
  {e:'🙀', name:'Cat Shock', cat:'faces', price:10, rarity:'common'},
  {e:'😿', name:'Cat Cry', cat:'faces', price:10, rarity:'common'},
  {e:'😾', name:'Cat Pout', cat:'faces', price:10, rarity:'common'},
  {e:'🙈', name:'See No Evil', cat:'faces', price:10, rarity:'common'},
  {e:'🙉', name:'Hear No Evil', cat:'faces', price:10, rarity:'common'},
  {e:'🙊', name:'Speak No Evil', cat:'faces', price:10, rarity:'common'},
  {e:'👶', name:'Baby', cat:'faces', price:150, rarity:'legendary'},
  {e:'🧒', name:'Child', cat:'faces', price:10, rarity:'common'},
  {e:'👦', name:'Boy', cat:'faces', price:25, rarity:'rare'},
  {e:'👧', name:'Girl', cat:'faces', price:10, rarity:'common'},
  {e:'🧑', name:'Person', cat:'faces', price:10, rarity:'common'},
  {e:'👨', name:'Man', cat:'faces', price:25, rarity:'rare'},
  {e:'👩', name:'Woman', cat:'faces', price:25, rarity:'rare'},
  {e:'🧓', name:'Older Person', cat:'faces', price:10, rarity:'common'},
  {e:'👴', name:'Old Man', cat:'faces', price:10, rarity:'common'},
  {e:'👵', name:'Old Woman', cat:'faces', price:10, rarity:'common'},
  {e:'👲', name:'Skullcap', cat:'faces', price:10, rarity:'common'},
  {e:'👳', name:'Turban', cat:'faces', price:10, rarity:'common'},
  {e:'🧕', name:'Headscarf', cat:'faces', price:10, rarity:'common'},
  {e:'👮', name:'Police', cat:'faces', price:25, rarity:'rare'},
  {e:'🕵️', name:'Detective', cat:'faces', price:150, rarity:'legendary'},
  {e:'💂', name:'Guard', cat:'faces', price:10, rarity:'common'},
  {e:'🥷', name:'Ninja', cat:'faces', price:10, rarity:'common'},
  {e:'👷', name:'Worker', cat:'faces', price:10, rarity:'common'},
  {e:'🫅', name:'Royalty', cat:'faces', price:25, rarity:'rare'},
  {e:'🤴', name:'Prince', cat:'faces', price:10, rarity:'common'},
  {e:'👸', name:'Princess', cat:'faces', price:25, rarity:'rare'},
  {e:'👰', name:'Bride', cat:'faces', price:10, rarity:'common'},
  {e:'🤵', name:'Tuxedo', cat:'faces', price:60, rarity:'epic'},
  {e:'🦸', name:'Hero', cat:'faces', price:25, rarity:'rare'},
  {e:'🦹', name:'Villain', cat:'faces', price:60, rarity:'epic'},
  {e:'🧙', name:'Mage', cat:'faces', price:10, rarity:'common'},
  {e:'🧚', name:'Fairy', cat:'faces', price:25, rarity:'rare'},
  {e:'🧛', name:'Vampire', cat:'faces', price:10, rarity:'common'},
  {e:'🧜', name:'Mermaid', cat:'faces', price:10, rarity:'common'},
  {e:'🧝', name:'Elf', cat:'faces', price:25, rarity:'rare'},
  {e:'🧞', name:'Genie', cat:'faces', price:10, rarity:'common'},
  {e:'🧟', name:'Zombie', cat:'faces', price:25, rarity:'rare'},
  {e:'💃', name:'Dancer', cat:'faces', price:10, rarity:'common'},
  {e:'🕺', name:'Disco', cat:'faces', price:10, rarity:'common'},
  {e:'👯', name:'Bunny Ears', cat:'faces', price:10, rarity:'common'},
  {e:'🧖', name:'Sauna', cat:'faces', price:10, rarity:'common'},
  {e:'🧗', name:'Climber', cat:'faces', price:10, rarity:'common'},
  {e:'🤺', name:'Fencer', cat:'faces', price:25, rarity:'rare'},
  {e:'🏇', name:'Jockey', cat:'faces', price:10, rarity:'common'},
  {e:'⛷️', name:'Skier', cat:'faces', price:25, rarity:'rare'},
  {e:'🏂', name:'Snowboarder', cat:'faces', price:10, rarity:'common'},
  {e:'🏌️', name:'Golfer', cat:'faces', price:25, rarity:'rare'},
  {e:'🏄', name:'Surfer', cat:'faces', price:25, rarity:'rare'},
  {e:'🚣', name:'Rowing', cat:'faces', price:10, rarity:'common'},
  {e:'🏊', name:'Swimmer', cat:'faces', price:25, rarity:'rare'},
  {e:'⛹️', name:'Bouncer', cat:'faces', price:10, rarity:'common'},
  {e:'🏋️', name:'Lifter', cat:'faces', price:10, rarity:'common'},
  {e:'🚴', name:'Cyclist', cat:'faces', price:10, rarity:'common'},
  {e:'🚵', name:'Mt Cyclist', cat:'faces', price:25, rarity:'rare'},
  {e:'🤸', name:'Cartwheel', cat:'faces', price:10, rarity:'common'},
  {e:'🤼', name:'Wrestlers', cat:'faces', price:10, rarity:'common'},
  {e:'🤽', name:'Water Polo', cat:'faces', price:60, rarity:'epic'},
  {e:'🤾', name:'Handball', cat:'faces', price:25, rarity:'rare'},
  {e:'🤹', name:'Juggler', cat:'faces', price:25, rarity:'rare'},
  {e:'🧘', name:'Lotus', cat:'faces', price:10, rarity:'common'},
  {e:'🐶', name:'Dog', cat:'animals', price:10, rarity:'common'},
  {e:'🐱', name:'Cat', cat:'animals', price:25, rarity:'rare'},
  {e:'🐭', name:'Mouse', cat:'animals', price:10, rarity:'common'},
  {e:'🐹', name:'Hamster', cat:'animals', price:60, rarity:'epic'},
  {e:'🐰', name:'Rabbit', cat:'animals', price:10, rarity:'common'},
  {e:'🦊', name:'Fox', cat:'animals', price:60, rarity:'epic'},
  {e:'🐻', name:'Bear', cat:'animals', price:25, rarity:'rare'},
  {e:'🐼', name:'Panda', cat:'animals', price:10, rarity:'common'},
  {e:'🐻‍❄️', name:'Polar Bear', cat:'animals', price:10, rarity:'common'},
  {e:'🐨', name:'Koala', cat:'animals', price:10, rarity:'common'},
  {e:'🐯', name:'Tiger', cat:'animals', price:25, rarity:'rare'},
  {e:'🦁', name:'Lion', cat:'animals', price:60, rarity:'epic'},
  {e:'🐮', name:'Cow', cat:'animals', price:150, rarity:'legendary'},
  {e:'🐷', name:'Pig', cat:'animals', price:150, rarity:'legendary'},
  {e:'🐽', name:'Pig Nose', cat:'animals', price:10, rarity:'common'},
  {e:'🐸', name:'Frog', cat:'animals', price:10, rarity:'common'},
  {e:'🐵', name:'Monkey', cat:'animals', price:25, rarity:'rare'},
  {e:'🙈', name:'No Evil See', cat:'animals', price:10, rarity:'common'},
  {e:'🙉', name:'No Evil Hear', cat:'animals', price:10, rarity:'common'},
  {e:'🙊', name:'No Evil Speak', cat:'animals', price:10, rarity:'common'},
  {e:'🐒', name:'Monkey Full', cat:'animals', price:10, rarity:'common'},
  {e:'🐔', name:'Chicken', cat:'animals', price:10, rarity:'common'},
  {e:'🐧', name:'Penguin', cat:'animals', price:10, rarity:'common'},
  {e:'🐦', name:'Bird', cat:'animals', price:25, rarity:'rare'},
  {e:'🐤', name:'Chick', cat:'animals', price:60, rarity:'epic'},
  {e:'🐣', name:'Hatching', cat:'animals', price:25, rarity:'rare'},
  {e:'🐥', name:'Front Chick', cat:'animals', price:25, rarity:'rare'},
  {e:'🦆', name:'Duck', cat:'animals', price:10, rarity:'common'},
  {e:'🦅', name:'Eagle', cat:'animals', price:10, rarity:'common'},
  {e:'🦉', name:'Owl', cat:'animals', price:10, rarity:'common'},
  {e:'🦇', name:'Bat', cat:'animals', price:150, rarity:'legendary'},
  {e:'🐺', name:'Wolf', cat:'animals', price:25, rarity:'rare'},
  {e:'🐗', name:'Boar', cat:'animals', price:10, rarity:'common'},
  {e:'🐴', name:'Horse Face', cat:'animals', price:10, rarity:'common'},
  {e:'🦄', name:'Unicorn', cat:'animals', price:10, rarity:'common'},
  {e:'🐝', name:'Bee', cat:'animals', price:60, rarity:'epic'},
  {e:'🪱', name:'Worm', cat:'animals', price:60, rarity:'epic'},
  {e:'🐛', name:'Bug', cat:'animals', price:60, rarity:'epic'},
  {e:'🦋', name:'Butterfly', cat:'animals', price:25, rarity:'rare'},
  {e:'🐌', name:'Snail', cat:'animals', price:10, rarity:'common'},
  {e:'🐞', name:'Lady Bug', cat:'animals', price:10, rarity:'common'},
  {e:'🐜', name:'Ant', cat:'animals', price:60, rarity:'epic'},
  {e:'🪰', name:'Fly', cat:'animals', price:60, rarity:'epic'},
  {e:'🪲', name:'Beetle', cat:'animals', price:25, rarity:'rare'},
  {e:'🦟', name:'Mosquito', cat:'animals', price:10, rarity:'common'},
  {e:'🦗', name:'Cricket', cat:'animals', price:10, rarity:'common'},
  {e:'🕷️', name:'Spider', cat:'animals', price:25, rarity:'rare'},
  {e:'🕸️', name:'Web', cat:'animals', price:60, rarity:'epic'},
  {e:'🦂', name:'Scorpion', cat:'animals', price:10, rarity:'common'},
  {e:'🐢', name:'Turtle', cat:'animals', price:25, rarity:'rare'},
  {e:'🐍', name:'Snake', cat:'animals', price:10, rarity:'common'},
  {e:'🦎', name:'Lizard', cat:'animals', price:10, rarity:'common'},
  {e:'🦖', name:'T-Rex', cat:'animals', price:10, rarity:'common'},
  {e:'🦕', name:'Sauropod', cat:'animals', price:10, rarity:'common'},
  {e:'🐙', name:'Octopus', cat:'animals', price:25, rarity:'rare'},
  {e:'🦑', name:'Squid', cat:'animals', price:10, rarity:'common'},
  {e:'🦐', name:'Shrimp', cat:'animals', price:60, rarity:'epic'},
  {e:'🦞', name:'Lobster', cat:'animals', price:25, rarity:'rare'},
  {e:'🦀', name:'Crab', cat:'animals', price:60, rarity:'epic'},
  {e:'🐡', name:'Blowfish', cat:'animals', price:10, rarity:'common'},
  {e:'🐠', name:'Tropical Fish', cat:'animals', price:10, rarity:'common'},
  {e:'🐟', name:'Fish', cat:'animals', price:25, rarity:'rare'},
  {e:'🐬', name:'Dolphin', cat:'animals', price:10, rarity:'common'},
  {e:'🐳', name:'Whale', cat:'animals', price:60, rarity:'epic'},
  {e:'🐋', name:'Big Whale', cat:'animals', price:10, rarity:'common'},
  {e:'🦈', name:'Shark', cat:'animals', price:10, rarity:'common'},
  {e:'🐊', name:'Crocodile', cat:'animals', price:10, rarity:'common'},
  {e:'🐅', name:'Tiger Full', cat:'animals', price:25, rarity:'rare'},
  {e:'🐆', name:'Leopard', cat:'animals', price:25, rarity:'rare'},
  {e:'🦓', name:'Zebra', cat:'animals', price:10, rarity:'common'},
  {e:'🦍', name:'Gorilla', cat:'animals', price:25, rarity:'rare'},
  {e:'🦧', name:'Orangutan', cat:'animals', price:25, rarity:'rare'},
  {e:'🐘', name:'Elephant', cat:'animals', price:10, rarity:'common'},
  {e:'🦣', name:'Mammoth', cat:'animals', price:10, rarity:'common'},
  {e:'🦛', name:'Hippo', cat:'animals', price:25, rarity:'rare'},
  {e:'🦏', name:'Rhino', cat:'animals', price:25, rarity:'rare'},
  {e:'🐪', name:'Camel', cat:'animals', price:60, rarity:'epic'},
  {e:'🐫', name:'Two Hump', cat:'animals', price:25, rarity:'rare'},
  {e:'🦒', name:'Giraffe', cat:'animals', price:10, rarity:'common'},
  {e:'🦘', name:'Kangaroo', cat:'animals', price:10, rarity:'common'},
  {e:'🦬', name:'Bison', cat:'animals', price:10, rarity:'common'},
  {e:'🐃', name:'Buffalo', cat:'animals', price:25, rarity:'rare'},
  {e:'🐂', name:'Ox', cat:'animals', price:10, rarity:'common'},
  {e:'🐄', name:'Cow Full', cat:'animals', price:25, rarity:'rare'},
  {e:'🐎', name:'Horse Full', cat:'animals', price:10, rarity:'common'},
  {e:'🐖', name:'Pig Full', cat:'animals', price:10, rarity:'common'},
  {e:'🐏', name:'Ram', cat:'animals', price:10, rarity:'common'},
  {e:'🐑', name:'Sheep', cat:'animals', price:25, rarity:'rare'},
  {e:'🦙', name:'Llama', cat:'animals', price:10, rarity:'common'},
  {e:'🐐', name:'Goat', cat:'animals', price:60, rarity:'epic'},
  {e:'🦌', name:'Deer', cat:'animals', price:10, rarity:'common'},
  {e:'🐕', name:'Dog Full', cat:'animals', price:10, rarity:'common'},
  {e:'🐩', name:'Poodle', cat:'animals', price:25, rarity:'rare'},
  {e:'🦮', name:'Service Dog', cat:'animals', price:150, rarity:'legendary'},
  {e:'🐕‍🦺', name:'Service', cat:'animals', price:10, rarity:'common'},
  {e:'🐈', name:'Cat Full', cat:'animals', price:10, rarity:'common'},
  {e:'🐈‍⬛', name:'Black Cat', cat:'animals', price:10, rarity:'common'},
  {e:'🐓', name:'Rooster', cat:'animals', price:60, rarity:'epic'},
  {e:'🦃', name:'Turkey', cat:'animals', price:10, rarity:'common'},
  {e:'🦚', name:'Peacock', cat:'animals', price:25, rarity:'rare'},
  {e:'🦜', name:'Parrot', cat:'animals', price:25, rarity:'rare'},
  {e:'🦢', name:'Swan', cat:'animals', price:25, rarity:'rare'},
  {e:'🦩', name:'Flamingo', cat:'animals', price:10, rarity:'common'},
  {e:'🕊️', name:'Dove', cat:'animals', price:10, rarity:'common'},
  {e:'🐇', name:'Rabbit Full', cat:'animals', price:10, rarity:'common'},
  {e:'🦝', name:'Raccoon', cat:'animals', price:10, rarity:'common'},
  {e:'🦨', name:'Skunk', cat:'animals', price:25, rarity:'rare'},
  {e:'🦡', name:'Badger', cat:'animals', price:25, rarity:'rare'},
  {e:'🦦', name:'Otter', cat:'animals', price:10, rarity:'common'},
  {e:'🦥', name:'Sloth', cat:'animals', price:10, rarity:'common'},
  {e:'🐁', name:'Mouse Full', cat:'animals', price:25, rarity:'rare'},
  {e:'🐀', name:'Rat', cat:'animals', price:25, rarity:'rare'},
  {e:'🐿️', name:'Chipmunk', cat:'animals', price:25, rarity:'rare'},
  {e:'🦔', name:'Hedgehog', cat:'animals', price:10, rarity:'common'},
  {e:'🐾', name:'Paw Prints', cat:'animals', price:10, rarity:'common'},
  {e:'🐉', name:'Dragon', cat:'animals', price:10, rarity:'common'},
  {e:'🐲', name:'Dragon Face', cat:'animals', price:150, rarity:'legendary'},
  {e:'🦂', name:'Scorpion Full', cat:'animals', price:10, rarity:'common'},
  {e:'🍎', name:'Red Apple', cat:'food', price:25, rarity:'rare'},
  {e:'🍏', name:'Green Apple', cat:'food', price:60, rarity:'epic'},
  {e:'🍊', name:'Orange', cat:'food', price:25, rarity:'rare'},
  {e:'🍋', name:'Lemon', cat:'food', price:10, rarity:'common'},
  {e:'🍌', name:'Banana', cat:'food', price:25, rarity:'rare'},
  {e:'🍉', name:'Watermelon', cat:'food', price:60, rarity:'epic'},
  {e:'🍇', name:'Grapes', cat:'food', price:60, rarity:'epic'},
  {e:'🍓', name:'Strawberry', cat:'food', price:10, rarity:'common'},
  {e:'🫐', name:'Blueberries', cat:'food', price:10, rarity:'common'},
  {e:'🍈', name:'Melon', cat:'food', price:10, rarity:'common'},
  {e:'🍒', name:'Cherries', cat:'food', price:25, rarity:'rare'},
  {e:'🍑', name:'Peach', cat:'food', price:10, rarity:'common'},
  {e:'🥭', name:'Mango', cat:'food', price:25, rarity:'rare'},
  {e:'🍍', name:'Pineapple', cat:'food', price:10, rarity:'common'},
  {e:'🥥', name:'Coconut', cat:'food', price:10, rarity:'common'},
  {e:'🥝', name:'Kiwi', cat:'food', price:150, rarity:'legendary'},
  {e:'🍅', name:'Tomato', cat:'food', price:10, rarity:'common'},
  {e:'🍆', name:'Eggplant', cat:'food', price:10, rarity:'common'},
  {e:'🥑', name:'Avocado', cat:'food', price:10, rarity:'common'},
  {e:'🥦', name:'Broccoli', cat:'food', price:10, rarity:'common'},
  {e:'🥬', name:'Leafy Green', cat:'food', price:10, rarity:'common'},
  {e:'🥒', name:'Cucumber', cat:'food', price:10, rarity:'common'},
  {e:'🌶️', name:'Pepper', cat:'food', price:60, rarity:'epic'},
  {e:'🫑', name:'Bell Pepper', cat:'food', price:25, rarity:'rare'},
  {e:'🌽', name:'Corn', cat:'food', price:25, rarity:'rare'},
  {e:'🥕', name:'Carrot', cat:'food', price:10, rarity:'common'},
  {e:'🫒', name:'Olive', cat:'food', price:60, rarity:'epic'},
  {e:'🧄', name:'Garlic', cat:'food', price:10, rarity:'common'},
  {e:'🧅', name:'Onion', cat:'food', price:60, rarity:'epic'},
  {e:'🥔', name:'Potato', cat:'food', price:150, rarity:'legendary'},
  {e:'🍠', name:'Sweet Potato', cat:'food', price:10, rarity:'common'},
  {e:'🥐', name:'Croissant', cat:'food', price:10, rarity:'common'},
  {e:'🥯', name:'Bagel', cat:'food', price:10, rarity:'common'},
  {e:'🍞', name:'Bread', cat:'food', price:10, rarity:'common'},
  {e:'🥖', name:'Baguette', cat:'food', price:10, rarity:'common'},
  {e:'🥨', name:'Pretzel', cat:'food', price:25, rarity:'rare'},
  {e:'🧀', name:'Cheese', cat:'food', price:10, rarity:'common'},
  {e:'🥚', name:'Egg', cat:'food', price:10, rarity:'common'},
  {e:'🍳', name:'Fried Egg', cat:'food', price:10, rarity:'common'},
  {e:'🧈', name:'Butter', cat:'food', price:10, rarity:'common'},
  {e:'🥞', name:'Pancakes', cat:'food', price:10, rarity:'common'},
  {e:'🧇', name:'Waffle', cat:'food', price:10, rarity:'common'},
  {e:'🥓', name:'Bacon', cat:'food', price:10, rarity:'common'},
  {e:'🥩', name:'Steak', cat:'food', price:60, rarity:'epic'},
  {e:'🍗', name:'Drumstick', cat:'food', price:10, rarity:'common'},
  {e:'🍖', name:'Meat', cat:'food', price:10, rarity:'common'},
  {e:'🦴', name:'Bone', cat:'food', price:150, rarity:'legendary'},
  {e:'🌭', name:'Hot Dog', cat:'food', price:10, rarity:'common'},
  {e:'🍔', name:'Burger', cat:'food', price:10, rarity:'common'},
  {e:'🍟', name:'Fries', cat:'food', price:25, rarity:'rare'},
  {e:'🍕', name:'Pizza', cat:'food', price:10, rarity:'common'},
  {e:'🥪', name:'Sandwich', cat:'food', price:10, rarity:'common'},
  {e:'🥙', name:'Stuffed Flat', cat:'food', price:25, rarity:'rare'},
  {e:'🧆', name:'Falafel', cat:'food', price:10, rarity:'common'},
  {e:'🌮', name:'Taco', cat:'food', price:25, rarity:'rare'},
  {e:'🌯', name:'Burrito', cat:'food', price:10, rarity:'common'},
  {e:'🫔', name:'Tamale', cat:'food', price:10, rarity:'common'},
  {e:'🥗', name:'Salad', cat:'food', price:10, rarity:'common'},
  {e:'🥘', name:'Pan', cat:'food', price:25, rarity:'rare'},
  {e:'🫕', name:'Fondue', cat:'food', price:10, rarity:'common'},
  {e:'🥫', name:'Canned', cat:'food', price:25, rarity:'rare'},
  {e:'🍝', name:'Spaghetti', cat:'food', price:25, rarity:'rare'},
  {e:'🍜', name:'Ramen', cat:'food', price:10, rarity:'common'},
  {e:'🍲', name:'Stew', cat:'food', price:10, rarity:'common'},
  {e:'🍛', name:'Curry', cat:'food', price:10, rarity:'common'},
  {e:'🍣', name:'Sushi', cat:'food', price:25, rarity:'rare'},
  {e:'🍱', name:'Bento', cat:'food', price:25, rarity:'rare'},
  {e:'🥟', name:'Dumpling', cat:'food', price:10, rarity:'common'},
  {e:'🦪', name:'Oyster', cat:'food', price:10, rarity:'common'},
  {e:'🍤', name:'Shrimp Fry', cat:'food', price:25, rarity:'rare'},
  {e:'🍙', name:'Rice Ball', cat:'food', price:10, rarity:'common'},
  {e:'🍚', name:'Rice', cat:'food', price:150, rarity:'legendary'},
  {e:'🍘', name:'Senbei', cat:'food', price:10, rarity:'common'},
  {e:'🍥', name:'Fish Cake', cat:'food', price:25, rarity:'rare'},
  {e:'🥠', name:'Fortune', cat:'food', price:10, rarity:'common'},
  {e:'🥮', name:'Mooncake', cat:'food', price:10, rarity:'common'},
  {e:'🍢', name:'Oden', cat:'food', price:25, rarity:'rare'},
  {e:'🍡', name:'Dango', cat:'food', price:10, rarity:'common'},
  {e:'🍧', name:'Shaved Ice', cat:'food', price:10, rarity:'common'},
  {e:'🍨', name:'Ice Cream', cat:'food', price:10, rarity:'common'},
  {e:'🍦', name:'Soft Serve', cat:'food', price:10, rarity:'common'},
  {e:'🥧', name:'Pie', cat:'food', price:10, rarity:'common'},
  {e:'🧁', name:'Cupcake', cat:'food', price:25, rarity:'rare'},
  {e:'🍰', name:'Cake Slice', cat:'food', price:60, rarity:'epic'},
  {e:'🎂', name:'Birthday', cat:'food', price:25, rarity:'rare'},
  {e:'🍮', name:'Custard', cat:'food', price:10, rarity:'common'},
  {e:'🍭', name:'Lollipop', cat:'food', price:10, rarity:'common'},
  {e:'🍬', name:'Candy', cat:'food', price:10, rarity:'common'},
  {e:'🍫', name:'Chocolate', cat:'food', price:60, rarity:'epic'},
  {e:'🍿', name:'Popcorn', cat:'food', price:25, rarity:'rare'},
  {e:'🍩', name:'Donut', cat:'food', price:150, rarity:'legendary'},
  {e:'🍪', name:'Cookie', cat:'food', price:10, rarity:'common'},
  {e:'🌰', name:'Chestnut', cat:'food', price:10, rarity:'common'},
  {e:'🥜', name:'Peanut', cat:'food', price:25, rarity:'rare'},
  {e:'🍯', name:'Honey', cat:'food', price:150, rarity:'legendary'},
  {e:'🥛', name:'Milk', cat:'food', price:10, rarity:'common'},
  {e:'🍼', name:'Bottle', cat:'food', price:10, rarity:'common'},
  {e:'🫖', name:'Teapot', cat:'food', price:25, rarity:'rare'},
  {e:'☕', name:'Coffee', cat:'food', price:10, rarity:'common'},
  {e:'🍵', name:'Tea', cat:'food', price:10, rarity:'common'},
  {e:'🧃', name:'Juice Box', cat:'food', price:10, rarity:'common'},
  {e:'🥤', name:'Cup Straw', cat:'food', price:10, rarity:'common'},
  {e:'🧋', name:'Bubble Tea', cat:'food', price:10, rarity:'common'},
  {e:'🍶', name:'Sake', cat:'food', price:60, rarity:'epic'},
  {e:'🍺', name:'Beer', cat:'food', price:10, rarity:'common'},
  {e:'🍻', name:'Cheers', cat:'food', price:10, rarity:'common'},
  {e:'🥂', name:'Champagne', cat:'food', price:25, rarity:'rare'},
  {e:'🍷', name:'Wine', cat:'food', price:25, rarity:'rare'},
  {e:'🥃', name:'Tumbler', cat:'food', price:60, rarity:'epic'},
  {e:'🍸', name:'Cocktail', cat:'food', price:10, rarity:'common'},
  {e:'🍹', name:'Tropical', cat:'food', price:10, rarity:'common'},
  {e:'🧉', name:'Mate', cat:'food', price:25, rarity:'rare'},
  {e:'🍾', name:'Bottle Pop', cat:'food', price:10, rarity:'common'},
  {e:'🧊', name:'Ice Cube', cat:'food', price:10, rarity:'common'},
  {e:'🥄', name:'Spoon', cat:'food', price:10, rarity:'common'},
  {e:'🍴', name:'Fork Knife', cat:'food', price:25, rarity:'rare'},
  {e:'🍽️', name:'Plate', cat:'food', price:25, rarity:'rare'},
  {e:'🥢', name:'Chopsticks', cat:'food', price:10, rarity:'common'},
  {e:'🧂', name:'Salt', cat:'food', price:60, rarity:'epic'},
  {e:'⚽', name:'Soccer', cat:'activities', price:10, rarity:'common'},
  {e:'🏀', name:'Basketball', cat:'activities', price:10, rarity:'common'},
  {e:'🏈', name:'Football', cat:'activities', price:10, rarity:'common'},
  {e:'⚾', name:'Baseball', cat:'activities', price:25, rarity:'rare'},
  {e:'🥎', name:'Softball', cat:'activities', price:10, rarity:'common'},
  {e:'🎾', name:'Tennis', cat:'activities', price:25, rarity:'rare'},
  {e:'🏐', name:'Volleyball', cat:'activities', price:10, rarity:'common'},
  {e:'🏉', name:'Rugby', cat:'activities', price:10, rarity:'common'},
  {e:'🥏', name:'Frisbee', cat:'activities', price:10, rarity:'common'},
  {e:'🎱', name:'8 Ball', cat:'activities', price:25, rarity:'rare'},
  {e:'🪀', name:'Yo-Yo', cat:'activities', price:25, rarity:'rare'},
  {e:'🏓', name:'Ping Pong', cat:'activities', price:25, rarity:'rare'},
  {e:'🏸', name:'Badminton', cat:'activities', price:25, rarity:'rare'},
  {e:'🥍', name:'Lacrosse', cat:'activities', price:10, rarity:'common'},
  {e:'🏒', name:'Hockey', cat:'activities', price:10, rarity:'common'},
  {e:'🏑', name:'Field Hockey', cat:'activities', price:10, rarity:'common'},
  {e:'🥌', name:'Curling', cat:'activities', price:10, rarity:'common'},
  {e:'⛷️', name:'Ski', cat:'activities', price:25, rarity:'rare'},
  {e:'🏂', name:'Snowboard Sport', cat:'activities', price:10, rarity:'common'},
  {e:'🪂', name:'Parachute', cat:'activities', price:10, rarity:'common'},
  {e:'🏋️', name:'Weightlift', cat:'activities', price:10, rarity:'common'},
  {e:'🤼', name:'Wrestle', cat:'activities', price:10, rarity:'common'},
  {e:'🤸', name:'Cartwheel Sport', cat:'activities', price:10, rarity:'common'},
  {e:'⛹️', name:'Ball Bounce', cat:'activities', price:10, rarity:'common'},
  {e:'🤺', name:'Fence', cat:'activities', price:25, rarity:'rare'},
  {e:'🤾', name:'Handball Sport', cat:'activities', price:25, rarity:'rare'},
  {e:'🏌️', name:'Golf', cat:'activities', price:25, rarity:'rare'},
  {e:'🏇', name:'Horse Race', cat:'activities', price:10, rarity:'common'},
  {e:'🧘', name:'Yoga', cat:'activities', price:10, rarity:'common'},
  {e:'🏄', name:'Surf', cat:'activities', price:25, rarity:'rare'},
  {e:'🏊', name:'Swim', cat:'activities', price:25, rarity:'rare'},
  {e:'🤽', name:'Polo', cat:'activities', price:60, rarity:'epic'},
  {e:'🚣', name:'Row', cat:'activities', price:10, rarity:'common'},
  {e:'🧗', name:'Climb', cat:'activities', price:10, rarity:'common'},
  {e:'🚵', name:'MTB', cat:'activities', price:25, rarity:'rare'},
  {e:'🚴', name:'Cycle', cat:'activities', price:10, rarity:'common'},
  {e:'🏆', name:'Trophy', cat:'activities', price:25, rarity:'rare'},
  {e:'🥇', name:'Gold', cat:'activities', price:10, rarity:'common'},
  {e:'🥈', name:'Silver', cat:'activities', price:10, rarity:'common'},
  {e:'🥉', name:'Bronze', cat:'activities', price:10, rarity:'common'},
  {e:'🏅', name:'Medal', cat:'activities', price:10, rarity:'common'},
  {e:'🎖️', name:'Military', cat:'activities', price:25, rarity:'rare'},
  {e:'🏵️', name:'Rosette', cat:'activities', price:60, rarity:'epic'},
  {e:'🎗️', name:'Ribbon', cat:'activities', price:25, rarity:'rare'},
  {e:'🎫', name:'Ticket', cat:'activities', price:25, rarity:'rare'},
  {e:'🎟️', name:'Admission', cat:'activities', price:10, rarity:'common'},
  {e:'🎪', name:'Circus', cat:'activities', price:25, rarity:'rare'},
  {e:'🤹', name:'Juggle', cat:'activities', price:25, rarity:'rare'},
  {e:'🎭', name:'Theater', cat:'activities', price:25, rarity:'rare'},
  {e:'🩰', name:'Ballet', cat:'activities', price:10, rarity:'common'},
  {e:'🎨', name:'Palette', cat:'activities', price:60, rarity:'epic'},
  {e:'🎬', name:'Clapper', cat:'activities', price:25, rarity:'rare'},
  {e:'🎤', name:'Mic', cat:'activities', price:10, rarity:'common'},
  {e:'🎧', name:'Headphones', cat:'activities', price:10, rarity:'common'},
  {e:'🎼', name:'Score', cat:'activities', price:25, rarity:'rare'},
  {e:'🎹', name:'Piano', cat:'activities', price:25, rarity:'rare'},
  {e:'🥁', name:'Drum', cat:'activities', price:10, rarity:'common'},
  {e:'🪘', name:'Long Drum', cat:'activities', price:60, rarity:'epic'},
  {e:'🎷', name:'Sax', cat:'activities', price:10, rarity:'common'},
  {e:'🎺', name:'Trumpet', cat:'activities', price:10, rarity:'common'},
  {e:'🎸', name:'Guitar', cat:'activities', price:150, rarity:'legendary'},
  {e:'🪕', name:'Banjo', cat:'activities', price:10, rarity:'common'},
  {e:'🎻', name:'Violin', cat:'activities', price:10, rarity:'common'},
  {e:'🪗', name:'Accordion', cat:'activities', price:10, rarity:'common'},
  {e:'🎲', name:'Die', cat:'activities', price:10, rarity:'common'},
  {e:'♟️', name:'Chess', cat:'activities', price:25, rarity:'rare'},
  {e:'🎯', name:'Target', cat:'activities', price:10, rarity:'common'},
  {e:'🎳', name:'Bowling', cat:'activities', price:60, rarity:'epic'},
  {e:'🎮', name:'Game', cat:'activities', price:10, rarity:'common'},
  {e:'🎰', name:'Slot', cat:'activities', price:25, rarity:'rare'},
  {e:'🧩', name:'Puzzle', cat:'activities', price:10, rarity:'common'},
  {e:'🪅', name:'Pinata', cat:'activities', price:10, rarity:'common'},
  {e:'🪆', name:'Nesting', cat:'activities', price:150, rarity:'legendary'},
  {e:'🚗', name:'Car', cat:'travel', price:10, rarity:'common'},
  {e:'🚕', name:'Taxi', cat:'travel', price:10, rarity:'common'},
  {e:'🚙', name:'SUV', cat:'travel', price:60, rarity:'epic'},
  {e:'🚌', name:'Bus', cat:'travel', price:25, rarity:'rare'},
  {e:'🚎', name:'Trolley', cat:'travel', price:10, rarity:'common'},
  {e:'🏎️', name:'Racing Car', cat:'travel', price:10, rarity:'common'},
  {e:'🚓', name:'Police Car', cat:'travel', price:10, rarity:'common'},
  {e:'🚑', name:'Ambulance', cat:'travel', price:60, rarity:'epic'},
  {e:'🚒', name:'Fire Truck', cat:'travel', price:60, rarity:'epic'},
  {e:'🚐', name:'Mini Bus', cat:'travel', price:10, rarity:'common'},
  {e:'🛻', name:'Pickup', cat:'travel', price:10, rarity:'common'},
  {e:'🚚', name:'Truck', cat:'travel', price:25, rarity:'rare'},
  {e:'🚛', name:'Articulated', cat:'travel', price:25, rarity:'rare'},
  {e:'🚜', name:'Tractor', cat:'travel', price:10, rarity:'common'},
  {e:'🛵', name:'Motor Scooter', cat:'travel', price:10, rarity:'common'},
  {e:'🏍️', name:'Motorcycle', cat:'travel', price:10, rarity:'common'},
  {e:'🛺', name:'Auto Rickshaw', cat:'travel', price:25, rarity:'rare'},
  {e:'🚲', name:'Bicycle', cat:'travel', price:25, rarity:'rare'},
  {e:'🛴', name:'Kick Scooter', cat:'travel', price:10, rarity:'common'},
  {e:'🛹', name:'Skateboard', cat:'travel', price:10, rarity:'common'},
  {e:'🛼', name:'Roller Skate', cat:'travel', price:10, rarity:'common'},
  {e:'🚏', name:'Bus Stop', cat:'travel', price:10, rarity:'common'},
  {e:'🛣️', name:'Motorway', cat:'travel', price:25, rarity:'rare'},
  {e:'🛤️', name:'Track', cat:'travel', price:10, rarity:'common'},
  {e:'🛢️', name:'Oil Drum', cat:'travel', price:10, rarity:'common'},
  {e:'⛽', name:'Fuel', cat:'travel', price:25, rarity:'rare'},
  {e:'🚨', name:'Light', cat:'travel', price:10, rarity:'common'},
  {e:'🚥', name:'Traffic Horiz', cat:'travel', price:10, rarity:'common'},
  {e:'🚦', name:'Traffic Vert', cat:'travel', price:10, rarity:'common'},
  {e:'🛑', name:'Stop', cat:'travel', price:60, rarity:'epic'},
  {e:'🚧', name:'Construction', cat:'travel', price:10, rarity:'common'},
  {e:'⚓', name:'Anchor', cat:'travel', price:10, rarity:'common'},
  {e:'⛵', name:'Sailboat', cat:'travel', price:10, rarity:'common'},
  {e:'🛶', name:'Canoe', cat:'travel', price:25, rarity:'rare'},
  {e:'🚤', name:'Speedboat', cat:'travel', price:10, rarity:'common'},
  {e:'🛳️', name:'Liner', cat:'travel', price:10, rarity:'common'},
  {e:'⛴️', name:'Ferry', cat:'travel', price:10, rarity:'common'},
  {e:'🛥️', name:'Motor Boat', cat:'travel', price:10, rarity:'common'},
  {e:'🚢', name:'Ship', cat:'travel', price:60, rarity:'epic'},
  {e:'✈️', name:'Plane', cat:'travel', price:25, rarity:'rare'},
  {e:'🛩️', name:'Small Plane', cat:'travel', price:10, rarity:'common'},
  {e:'🛫', name:'Takeoff', cat:'travel', price:25, rarity:'rare'},
  {e:'🛬', name:'Landing', cat:'travel', price:60, rarity:'epic'},
  {e:'🪂', name:'Parachute Travel', cat:'travel', price:10, rarity:'common'},
  {e:'💺', name:'Seat', cat:'travel', price:10, rarity:'common'},
  {e:'🚀', name:'Rocket', cat:'travel', price:10, rarity:'common'},
  {e:'🛸', name:'UFO', cat:'travel', price:10, rarity:'common'},
  {e:'🚁', name:'Helicopter', cat:'travel', price:10, rarity:'common'},
  {e:'🛶', name:'Canoe Travel', cat:'travel', price:25, rarity:'rare'},
  {e:'⛺', name:'Tent', cat:'travel', price:25, rarity:'rare'},
  {e:'🪐', name:'Saturn', cat:'travel', price:10, rarity:'common'},
  {e:'☀️', name:'Sun', cat:'travel', price:60, rarity:'epic'},
  {e:'🌙', name:'Moon', cat:'travel', price:60, rarity:'epic'},
  {e:'⭐', name:'Star', cat:'travel', price:10, rarity:'common'},
  {e:'🌟', name:'Glowing Star', cat:'travel', price:25, rarity:'rare'},
  {e:'✨', name:'Sparkles', cat:'travel', price:25, rarity:'rare'},
  {e:'⚡', name:'Lightning', cat:'travel', price:10, rarity:'common'},
  {e:'☄️', name:'Comet', cat:'travel', price:10, rarity:'common'},
  {e:'💫', name:'Dizzy', cat:'travel', price:60, rarity:'epic'},
  {e:'🌈', name:'Rainbow', cat:'travel', price:25, rarity:'rare'},
  {e:'☁️', name:'Cloud', cat:'travel', price:10, rarity:'common'},
  {e:'⛅', name:'Sun Cloud', cat:'travel', price:25, rarity:'rare'},
  {e:'⛈️', name:'Storm', cat:'travel', price:10, rarity:'common'},
  {e:'🌤️', name:'Mostly Sun', cat:'travel', price:10, rarity:'common'},
  {e:'🌥️', name:'Mostly Cloud', cat:'travel', price:25, rarity:'rare'},
  {e:'🌦️', name:'Rain Sun', cat:'travel', price:10, rarity:'common'},
  {e:'🌧️', name:'Rain', cat:'travel', price:25, rarity:'rare'},
  {e:'🌨️', name:'Snow', cat:'travel', price:10, rarity:'common'},
  {e:'🌩️', name:'Lightning Cloud', cat:'travel', price:25, rarity:'rare'},
  {e:'🌪️', name:'Tornado', cat:'travel', price:60, rarity:'epic'},
  {e:'🌫️', name:'Fog', cat:'travel', price:10, rarity:'common'},
  {e:'🌬️', name:'Wind', cat:'travel', price:10, rarity:'common'},
  {e:'🌀', name:'Cyclone', cat:'travel', price:10, rarity:'common'},
  {e:'🌊', name:'Wave', cat:'travel', price:60, rarity:'epic'},
  {e:'🔥', name:'Fire', cat:'travel', price:150, rarity:'legendary'},
  {e:'💧', name:'Drop', cat:'travel', price:10, rarity:'common'},
  {e:'❄️', name:'Snowflake', cat:'travel', price:10, rarity:'common'},
  {e:'☃️', name:'Snowman', cat:'travel', price:10, rarity:'common'},
  {e:'⛄', name:'Snowman Plain', cat:'travel', price:60, rarity:'epic'},
  {e:'🗻', name:'Mt Fuji', cat:'travel', price:10, rarity:'common'},
  {e:'🏔️', name:'Mountain', cat:'travel', price:10, rarity:'common'},
  {e:'⛰️', name:'Mountain Plain', cat:'travel', price:60, rarity:'epic'},
  {e:'🌋', name:'Volcano', cat:'travel', price:25, rarity:'rare'},
  {e:'🏕️', name:'Camping', cat:'travel', price:10, rarity:'common'},
  {e:'🏖️', name:'Beach', cat:'travel', price:10, rarity:'common'},
  {e:'🏜️', name:'Desert', cat:'travel', price:25, rarity:'rare'},
  {e:'🏝️', name:'Island', cat:'travel', price:10, rarity:'common'},
  {e:'🌅', name:'Sunrise', cat:'travel', price:10, rarity:'common'},
  {e:'🌄', name:'Sunrise Mt', cat:'travel', price:10, rarity:'common'},
  {e:'🌠', name:'Shooting Star', cat:'travel', price:25, rarity:'rare'},
  {e:'🎆', name:'Fireworks', cat:'travel', price:10, rarity:'common'},
  {e:'🎇', name:'Sparkler', cat:'travel', price:10, rarity:'common'},
  {e:'🌃', name:'Night City', cat:'travel', price:10, rarity:'common'},
  {e:'🌆', name:'Sunset City', cat:'travel', price:10, rarity:'common'},
  {e:'🌇', name:'Sunset', cat:'travel', price:10, rarity:'common'},
  {e:'🏙️', name:'Cityscape', cat:'travel', price:10, rarity:'common'},
  {e:'🌉', name:'Bridge', cat:'travel', price:10, rarity:'common'},
  {e:'⌚', name:'Watch', cat:'objects', price:25, rarity:'rare'},
  {e:'📱', name:'Phone', cat:'objects', price:10, rarity:'common'},
  {e:'💻', name:'Laptop', cat:'objects', price:60, rarity:'epic'},
  {e:'⌨️', name:'Keyboard', cat:'objects', price:10, rarity:'common'},
  {e:'🖥️', name:'Desktop', cat:'objects', price:10, rarity:'common'},
  {e:'🖨️', name:'Printer', cat:'objects', price:25, rarity:'rare'},
  {e:'🖱️', name:'Mouse Dev', cat:'objects', price:10, rarity:'common'},
  {e:'🕹️', name:'Joystick', cat:'objects', price:10, rarity:'common'},
  {e:'💾', name:'Floppy', cat:'objects', price:10, rarity:'common'},
  {e:'💿', name:'CD', cat:'objects', price:10, rarity:'common'},
  {e:'📀', name:'DVD', cat:'objects', price:10, rarity:'common'},
  {e:'📷', name:'Camera', cat:'objects', price:150, rarity:'legendary'},
  {e:'📸', name:'Flash Camera', cat:'objects', price:10, rarity:'common'},
  {e:'📹', name:'Video Camera', cat:'objects', price:60, rarity:'epic'},
  {e:'🎥', name:'Movie Camera', cat:'objects', price:25, rarity:'rare'},
  {e:'📞', name:'Telephone', cat:'objects', price:10, rarity:'common'},
  {e:'☎️', name:'Phone Old', cat:'objects', price:10, rarity:'common'},
  {e:'📟', name:'Pager', cat:'objects', price:10, rarity:'common'},
  {e:'📠', name:'Fax', cat:'objects', price:10, rarity:'common'},
  {e:'📺', name:'TV', cat:'objects', price:10, rarity:'common'},
  {e:'📻', name:'Radio', cat:'objects', price:10, rarity:'common'},
  {e:'🎙️', name:'Studio Mic', cat:'objects', price:25, rarity:'rare'},
  {e:'🎚️', name:'Slider', cat:'objects', price:10, rarity:'common'},
  {e:'🎛️', name:'Knobs', cat:'objects', price:60, rarity:'epic'},
  {e:'⏱️', name:'Stopwatch', cat:'objects', price:10, rarity:'common'},
  {e:'⏲️', name:'Timer', cat:'objects', price:25, rarity:'rare'},
  {e:'⏰', name:'Alarm', cat:'objects', price:10, rarity:'common'},
  {e:'🕰️', name:'Mantel Clock', cat:'objects', price:25, rarity:'rare'},
  {e:'⌛', name:'Hourglass', cat:'objects', price:60, rarity:'epic'},
  {e:'⏳', name:'Hourglass Run', cat:'objects', price:10, rarity:'common'},
  {e:'📡', name:'Satellite', cat:'objects', price:25, rarity:'rare'},
  {e:'🔋', name:'Battery', cat:'objects', price:10, rarity:'common'},
  {e:'🔌', name:'Plug', cat:'objects', price:60, rarity:'epic'},
  {e:'💡', name:'Lightbulb', cat:'objects', price:150, rarity:'legendary'},
  {e:'🔦', name:'Flashlight', cat:'objects', price:25, rarity:'rare'},
  {e:'🕯️', name:'Candle', cat:'objects', price:25, rarity:'rare'},
  {e:'🪔', name:'Diya', cat:'objects', price:10, rarity:'common'},
  {e:'🧯', name:'Extinguisher', cat:'objects', price:25, rarity:'rare'},
  {e:'🛢️', name:'Drum Object', cat:'objects', price:10, rarity:'common'},
  {e:'💸', name:'Wing Money', cat:'objects', price:10, rarity:'common'},
  {e:'💵', name:'Dollar', cat:'objects', price:60, rarity:'epic'},
  {e:'💴', name:'Yen', cat:'objects', price:25, rarity:'rare'},
  {e:'💶', name:'Euro', cat:'objects', price:25, rarity:'rare'},
  {e:'💷', name:'Pound', cat:'objects', price:25, rarity:'rare'},
  {e:'🪙', name:'Coin', cat:'objects', price:10, rarity:'common'},
  {e:'💰', name:'Money Bag', cat:'objects', price:10, rarity:'common'},
  {e:'💳', name:'Credit Card', cat:'objects', price:10, rarity:'common'},
  {e:'💎', name:'Gem', cat:'objects', price:10, rarity:'common'},
  {e:'⚖️', name:'Balance', cat:'objects', price:10, rarity:'common'},
  {e:'🪜', name:'Ladder', cat:'objects', price:10, rarity:'common'},
  {e:'🧰', name:'Toolbox', cat:'objects', price:10, rarity:'common'},
  {e:'🪛', name:'Screwdriver', cat:'objects', price:25, rarity:'rare'},
  {e:'🔧', name:'Wrench', cat:'objects', price:10, rarity:'common'},
  {e:'🔨', name:'Hammer', cat:'objects', price:10, rarity:'common'},
  {e:'⚒️', name:'Hammer Pick', cat:'objects', price:10, rarity:'common'},
  {e:'🛠️', name:'Hammer Wrench', cat:'objects', price:25, rarity:'rare'},
  {e:'⛏️', name:'Pick', cat:'objects', price:10, rarity:'common'},
  {e:'🪚', name:'Saw', cat:'objects', price:25, rarity:'rare'},
  {e:'🔩', name:'Bolt Nut', cat:'objects', price:10, rarity:'common'},
  {e:'⚙️', name:'Gear', cat:'objects', price:10, rarity:'common'},
  {e:'🪤', name:'Mouse Trap', cat:'objects', price:25, rarity:'rare'},
  {e:'🧱', name:'Brick', cat:'objects', price:60, rarity:'epic'},
  {e:'⛓️', name:'Chain', cat:'objects', price:10, rarity:'common'},
  {e:'🧲', name:'Magnet', cat:'objects', price:10, rarity:'common'},
  {e:'🔫', name:'Water Gun', cat:'objects', price:10, rarity:'common'},
  {e:'💣', name:'Bomb', cat:'objects', price:25, rarity:'rare'},
  {e:'🧨', name:'Firecracker', cat:'objects', price:10, rarity:'common'},
  {e:'🪓', name:'Axe', cat:'objects', price:10, rarity:'common'},
  {e:'🔪', name:'Knife', cat:'objects', price:10, rarity:'common'},
  {e:'🗡️', name:'Dagger', cat:'objects', price:10, rarity:'common'},
  {e:'⚔️', name:'Crossed Swords', cat:'objects', price:150, rarity:'legendary'},
  {e:'🛡️', name:'Shield', cat:'objects', price:10, rarity:'common'},
  {e:'🚬', name:'Cigarette', cat:'objects', price:25, rarity:'rare'},
  {e:'⚰️', name:'Coffin', cat:'objects', price:10, rarity:'common'},
  {e:'🪦', name:'Headstone', cat:'objects', price:60, rarity:'epic'},
  {e:'⚱️', name:'Urn', cat:'objects', price:25, rarity:'rare'},
  {e:'🏺', name:'Amphora', cat:'objects', price:25, rarity:'rare'},
  {e:'🔮', name:'Crystal', cat:'objects', price:10, rarity:'common'},
  {e:'📿', name:'Beads', cat:'objects', price:10, rarity:'common'},
  {e:'🧿', name:'Eye', cat:'objects', price:10, rarity:'common'},
  {e:'🪬', name:'Hamsa', cat:'objects', price:10, rarity:'common'},
  {e:'💈', name:'Barber', cat:'objects', price:10, rarity:'common'},
  {e:'⚗️', name:'Alembic', cat:'objects', price:10, rarity:'common'},
  {e:'🔭', name:'Telescope', cat:'objects', price:25, rarity:'rare'},
  {e:'🔬', name:'Microscope', cat:'objects', price:10, rarity:'common'},
  {e:'🕳️', name:'Hole', cat:'objects', price:10, rarity:'common'},
  {e:'🩹', name:'Bandage', cat:'objects', price:25, rarity:'rare'},
  {e:'🩺', name:'Stethoscope', cat:'objects', price:10, rarity:'common'},
  {e:'💊', name:'Pill', cat:'objects', price:25, rarity:'rare'},
  {e:'💉', name:'Syringe', cat:'objects', price:10, rarity:'common'},
  {e:'🩸', name:'Drop Blood', cat:'objects', price:10, rarity:'common'},
  {e:'🧬', name:'DNA', cat:'objects', price:25, rarity:'rare'},
  {e:'🦠', name:'Microbe', cat:'objects', price:60, rarity:'epic'},
  {e:'🧫', name:'Petri', cat:'objects', price:10, rarity:'common'},
  {e:'🧪', name:'Test Tube', cat:'objects', price:10, rarity:'common'},
  {e:'🌡️', name:'Thermometer', cat:'objects', price:60, rarity:'epic'},
  {e:'🧹', name:'Broom', cat:'objects', price:10, rarity:'common'},
  {e:'🧺', name:'Basket', cat:'objects', price:25, rarity:'rare'},
  {e:'🧻', name:'Roll', cat:'objects', price:10, rarity:'common'},
  {e:'🪣', name:'Bucket', cat:'objects', price:25, rarity:'rare'},
  {e:'🧼', name:'Soap', cat:'objects', price:25, rarity:'rare'},
  {e:'🪥', name:'Toothbrush', cat:'objects', price:60, rarity:'epic'},
  {e:'🧽', name:'Sponge', cat:'objects', price:60, rarity:'epic'},
  {e:'🪒', name:'Razor', cat:'objects', price:25, rarity:'rare'},
  {e:'🧴', name:'Lotion', cat:'objects', price:60, rarity:'epic'},
  {e:'🛎️', name:'Bell', cat:'objects', price:25, rarity:'rare'},
  {e:'🔑', name:'Key', cat:'objects', price:10, rarity:'common'},
  {e:'🗝️', name:'Old Key', cat:'objects', price:10, rarity:'common'},
  {e:'🚪', name:'Door', cat:'objects', price:10, rarity:'common'},
  {e:'🪑', name:'Chair', cat:'objects', price:25, rarity:'rare'},
  {e:'🛋️', name:'Couch', cat:'objects', price:60, rarity:'epic'},
  {e:'🛏️', name:'Bed', cat:'objects', price:10, rarity:'common'},
  {e:'🛌', name:'Sleeping Bed', cat:'objects', price:10, rarity:'common'},
  {e:'🧸', name:'Teddy', cat:'objects', price:25, rarity:'rare'},
  {e:'🪆', name:'Matryoshka', cat:'objects', price:150, rarity:'legendary'},
  {e:'🖼️', name:'Picture', cat:'objects', price:10, rarity:'common'},
  {e:'🪞', name:'Mirror', cat:'objects', price:10, rarity:'common'},
  {e:'🪟', name:'Window', cat:'objects', price:25, rarity:'rare'},
  {e:'🛍️', name:'Bags', cat:'objects', price:10, rarity:'common'},
  {e:'🛒', name:'Shopping', cat:'objects', price:10, rarity:'common'},
  {e:'🎁', name:'Gift', cat:'objects', price:10, rarity:'common'},
  {e:'🎈', name:'Balloon', cat:'objects', price:10, rarity:'common'},
  {e:'🎏', name:'Carp Streamer', cat:'objects', price:10, rarity:'common'},
  {e:'🎀', name:'Ribbon Bow', cat:'objects', price:150, rarity:'legendary'},
  {e:'🎊', name:'Confetti', cat:'objects', price:60, rarity:'epic'},
  {e:'🎉', name:'Party Popper', cat:'objects', price:10, rarity:'common'},
  {e:'🎎', name:'Dolls', cat:'objects', price:10, rarity:'common'},
  {e:'🏮', name:'Lantern', cat:'objects', price:10, rarity:'common'},
  {e:'🎐', name:'Wind Chime', cat:'objects', price:10, rarity:'common'},
  {e:'✉️', name:'Envelope', cat:'objects', price:10, rarity:'common'},
  {e:'📩', name:'Incoming', cat:'objects', price:10, rarity:'common'},
  {e:'📨', name:'Mail Receive', cat:'objects', price:60, rarity:'epic'},
  {e:'📧', name:'Email', cat:'objects', price:25, rarity:'rare'},
  {e:'💌', name:'Love Letter', cat:'objects', price:10, rarity:'common'},
  {e:'📥', name:'Inbox', cat:'objects', price:150, rarity:'legendary'},
  {e:'📤', name:'Outbox', cat:'objects', price:60, rarity:'epic'},
  {e:'📦', name:'Package', cat:'objects', price:25, rarity:'rare'},
  {e:'🏷️', name:'Tag', cat:'objects', price:10, rarity:'common'},
  {e:'📪', name:'Closed Mailbox', cat:'objects', price:25, rarity:'rare'},
  {e:'📫', name:'Mailbox', cat:'objects', price:10, rarity:'common'},
  {e:'📬', name:'Open Mailbox', cat:'objects', price:25, rarity:'rare'},
  {e:'📭', name:'No Mail', cat:'objects', price:25, rarity:'rare'},
  {e:'📮', name:'Postbox', cat:'objects', price:60, rarity:'epic'},
  {e:'📯', name:'Horn', cat:'objects', price:10, rarity:'common'},
  {e:'📜', name:'Scroll', cat:'objects', price:10, rarity:'common'},
  {e:'📃', name:'Page Curl', cat:'objects', price:25, rarity:'rare'},
  {e:'📄', name:'Page', cat:'objects', price:25, rarity:'rare'},
  {e:'📑', name:'Bookmark Tabs', cat:'objects', price:60, rarity:'epic'},
  {e:'🧾', name:'Receipt', cat:'objects', price:10, rarity:'common'},
  {e:'📊', name:'Bar Chart', cat:'objects', price:10, rarity:'common'},
  {e:'📈', name:'Up Chart', cat:'objects', price:10, rarity:'common'},
  {e:'📉', name:'Down Chart', cat:'objects', price:10, rarity:'common'},
  {e:'🗒️', name:'Spiral Pad', cat:'objects', price:10, rarity:'common'},
  {e:'🗓️', name:'Spiral Cal', cat:'objects', price:10, rarity:'common'},
  {e:'📆', name:'Tear Cal', cat:'objects', price:25, rarity:'rare'},
  {e:'📅', name:'Calendar', cat:'objects', price:10, rarity:'common'},
  {e:'🗑️', name:'Trash', cat:'objects', price:10, rarity:'common'},
  {e:'📇', name:'Card Index', cat:'objects', price:10, rarity:'common'},
  {e:'🗃️', name:'Card Box', cat:'objects', price:10, rarity:'common'},
  {e:'🗳️', name:'Ballot', cat:'objects', price:10, rarity:'common'},
  {e:'🗄️', name:'Cabinet', cat:'objects', price:25, rarity:'rare'},
  {e:'📋', name:'Clipboard', cat:'objects', price:150, rarity:'legendary'},
  {e:'📁', name:'Folder', cat:'objects', price:10, rarity:'common'},
  {e:'📂', name:'Open Folder', cat:'objects', price:10, rarity:'common'},
  {e:'🗂️', name:'Dividers', cat:'objects', price:10, rarity:'common'},
  {e:'🗞️', name:'Newspaper Roll', cat:'objects', price:10, rarity:'common'},
  {e:'📰', name:'Newspaper', cat:'objects', price:25, rarity:'rare'},
  {e:'📓', name:'Notebook', cat:'objects', price:10, rarity:'common'},
  {e:'📔', name:'Decor Notebook', cat:'objects', price:25, rarity:'rare'},
  {e:'📒', name:'Ledger', cat:'objects', price:10, rarity:'common'},
  {e:'📕', name:'Book Red', cat:'objects', price:25, rarity:'rare'},
  {e:'📗', name:'Book Green', cat:'objects', price:10, rarity:'common'},
  {e:'📘', name:'Book Blue', cat:'objects', price:10, rarity:'common'},
  {e:'📙', name:'Book Orange', cat:'objects', price:25, rarity:'rare'},
  {e:'📚', name:'Books', cat:'objects', price:10, rarity:'common'},
  {e:'📖', name:'Open Book', cat:'objects', price:10, rarity:'common'},
  {e:'🔖', name:'Bookmark', cat:'objects', price:25, rarity:'rare'},
  {e:'🔗', name:'Link', cat:'objects', price:10, rarity:'common'},
  {e:'📎', name:'Paperclip', cat:'objects', price:10, rarity:'common'},
  {e:'🖇️', name:'Linked Clip', cat:'objects', price:60, rarity:'epic'},
  {e:'📐', name:'Triangle Ruler', cat:'objects', price:60, rarity:'epic'},
  {e:'📏', name:'Ruler', cat:'objects', price:60, rarity:'epic'},
  {e:'🧮', name:'Abacus', cat:'objects', price:150, rarity:'legendary'},
  {e:'📌', name:'Pushpin', cat:'objects', price:10, rarity:'common'},
  {e:'📍', name:'Round Pushpin', cat:'objects', price:25, rarity:'rare'},
  {e:'✂️', name:'Scissors', cat:'objects', price:150, rarity:'legendary'},
  {e:'🖊️', name:'Pen', cat:'objects', price:25, rarity:'rare'},
  {e:'🖋️', name:'Fountain Pen', cat:'objects', price:10, rarity:'common'},
  {e:'✒️', name:'Black Nib', cat:'objects', price:10, rarity:'common'},
  {e:'🖌️', name:'Brush', cat:'objects', price:10, rarity:'common'},
  {e:'🖍️', name:'Crayon', cat:'objects', price:10, rarity:'common'},
  {e:'📝', name:'Memo', cat:'objects', price:25, rarity:'rare'},
  {e:'✏️', name:'Pencil', cat:'objects', price:25, rarity:'rare'},
  {e:'🔍', name:'Magnifier Left', cat:'objects', price:150, rarity:'legendary'},
  {e:'🔎', name:'Magnifier Right', cat:'objects', price:10, rarity:'common'},
  {e:'🔏', name:'Locked Pen', cat:'objects', price:10, rarity:'common'},
  {e:'🔐', name:'Locked Key', cat:'objects', price:60, rarity:'epic'},
  {e:'🔒', name:'Locked', cat:'objects', price:25, rarity:'rare'},
  {e:'🔓', name:'Unlocked', cat:'objects', price:10, rarity:'common'},
  {e:'🪨', name:'Rock', cat:'objects', price:10, rarity:'common'},
  {e:'🪵', name:'Wood', cat:'objects', price:10, rarity:'common'},
  {e:'❤️', name:'Red Heart', cat:'symbols', price:10, rarity:'common'},
  {e:'🧡', name:'Orange Heart', cat:'symbols', price:10, rarity:'common'},
  {e:'💛', name:'Yellow Heart', cat:'symbols', price:10, rarity:'common'},
  {e:'💚', name:'Green Heart', cat:'symbols', price:25, rarity:'rare'},
  {e:'💙', name:'Blue Heart', cat:'symbols', price:10, rarity:'common'},
  {e:'💜', name:'Purple Heart', cat:'symbols', price:10, rarity:'common'},
  {e:'🖤', name:'Black Heart', cat:'symbols', price:10, rarity:'common'},
  {e:'🤍', name:'White Heart', cat:'symbols', price:10, rarity:'common'},
  {e:'🤎', name:'Brown Heart', cat:'symbols', price:10, rarity:'common'},
  {e:'💔', name:'Broken', cat:'symbols', price:25, rarity:'rare'},
  {e:'❣️', name:'Heart Excl', cat:'symbols', price:25, rarity:'rare'},
  {e:'💕', name:'Two Hearts', cat:'symbols', price:10, rarity:'common'},
  {e:'💞', name:'Revolving', cat:'symbols', price:10, rarity:'common'},
  {e:'💓', name:'Beating', cat:'symbols', price:60, rarity:'epic'},
  {e:'💗', name:'Growing', cat:'symbols', price:25, rarity:'rare'},
  {e:'💖', name:'Sparkling', cat:'symbols', price:10, rarity:'common'},
  {e:'💘', name:'Heart Arrow', cat:'symbols', price:25, rarity:'rare'},
  {e:'💝', name:'Ribbon Heart', cat:'symbols', price:10, rarity:'common'},
  {e:'💟', name:'Heart Decor', cat:'symbols', price:150, rarity:'legendary'},
  {e:'☮️', name:'Peace', cat:'symbols', price:10, rarity:'common'},
  {e:'✝️', name:'Cross', cat:'symbols', price:10, rarity:'common'},
  {e:'☪️', name:'Crescent', cat:'symbols', price:25, rarity:'rare'},
  {e:'🕉️', name:'Om', cat:'symbols', price:10, rarity:'common'},
  {e:'☸️', name:'Wheel', cat:'symbols', price:25, rarity:'rare'},
  {e:'✡️', name:'Star David', cat:'symbols', price:10, rarity:'common'},
  {e:'🔯', name:'Six Star', cat:'symbols', price:10, rarity:'common'},
  {e:'🕎', name:'Menorah', cat:'symbols', price:10, rarity:'common'},
  {e:'☯️', name:'Yin Yang', cat:'symbols', price:25, rarity:'rare'},
  {e:'☦️', name:'Orthodox', cat:'symbols', price:60, rarity:'epic'},
  {e:'🛐', name:'Worship', cat:'symbols', price:60, rarity:'epic'},
  {e:'⛎', name:'Ophiuchus', cat:'symbols', price:25, rarity:'rare'},
  {e:'♈', name:'Aries', cat:'symbols', price:25, rarity:'rare'},
  {e:'♉', name:'Taurus', cat:'symbols', price:10, rarity:'common'},
  {e:'♊', name:'Gemini', cat:'symbols', price:25, rarity:'rare'},
  {e:'♋', name:'Cancer', cat:'symbols', price:10, rarity:'common'},
  {e:'♌', name:'Leo', cat:'symbols', price:10, rarity:'common'},
  {e:'♍', name:'Virgo', cat:'symbols', price:150, rarity:'legendary'},
  {e:'♎', name:'Libra', cat:'symbols', price:25, rarity:'rare'},
  {e:'♏', name:'Scorpio', cat:'symbols', price:25, rarity:'rare'},
  {e:'♐', name:'Sagittarius', cat:'symbols', price:25, rarity:'rare'},
  {e:'♑', name:'Capricorn', cat:'symbols', price:60, rarity:'epic'},
  {e:'♒', name:'Aquarius', cat:'symbols', price:25, rarity:'rare'},
  {e:'♓', name:'Pisces', cat:'symbols', price:10, rarity:'common'},
  {e:'🆔', name:'ID', cat:'symbols', price:10, rarity:'common'},
  {e:'⚛️', name:'Atom', cat:'symbols', price:10, rarity:'common'},
  {e:'🉑', name:'Accept', cat:'symbols', price:25, rarity:'rare'},
  {e:'☢️', name:'Radioactive', cat:'symbols', price:25, rarity:'rare'},
  {e:'☣️', name:'Biohazard', cat:'symbols', price:10, rarity:'common'},
  {e:'📴', name:'Phone Off', cat:'symbols', price:10, rarity:'common'},
  {e:'📳', name:'Vibration', cat:'symbols', price:10, rarity:'common'},
  {e:'🈶', name:'Not Free', cat:'symbols', price:10, rarity:'common'},
  {e:'🈚', name:'Free', cat:'symbols', price:150, rarity:'legendary'},
  {e:'🈸', name:'Application', cat:'symbols', price:10, rarity:'common'},
  {e:'🈺', name:'Open Business', cat:'symbols', price:10, rarity:'common'},
  {e:'🈷️', name:'Monthly', cat:'symbols', price:25, rarity:'rare'},
  {e:'✴️', name:'Eight Star', cat:'symbols', price:60, rarity:'epic'},
  {e:'🆚', name:'VS', cat:'symbols', price:10, rarity:'common'},
  {e:'💮', name:'White Flower', cat:'symbols', price:60, rarity:'epic'},
  {e:'🉐', name:'Bargain', cat:'symbols', price:10, rarity:'common'},
  {e:'㊙️', name:'Secret', cat:'symbols', price:10, rarity:'common'},
  {e:'㊗️', name:'Congrats', cat:'symbols', price:10, rarity:'common'},
  {e:'🈴', name:'Pass', cat:'symbols', price:10, rarity:'common'},
  {e:'🈵', name:'No Vacancy', cat:'symbols', price:10, rarity:'common'},
  {e:'🈹', name:'Discount', cat:'symbols', price:10, rarity:'common'},
  {e:'🈲', name:'Prohibited', cat:'symbols', price:25, rarity:'rare'},
  {e:'🅰️', name:'A Type', cat:'symbols', price:10, rarity:'common'},
  {e:'🅱️', name:'B Type', cat:'symbols', price:10, rarity:'common'},
  {e:'🆎', name:'AB Type', cat:'symbols', price:10, rarity:'common'},
  {e:'🆑', name:'CL', cat:'symbols', price:10, rarity:'common'},
  {e:'🅾️', name:'O Type', cat:'symbols', price:10, rarity:'common'},
  {e:'🆘', name:'SOS', cat:'symbols', price:10, rarity:'common'},
  {e:'❌', name:'Cross Mark', cat:'symbols', price:10, rarity:'common'},
  {e:'⭕', name:'Hollow Circle', cat:'symbols', price:25, rarity:'rare'},
  {e:'🛑', name:'Octagon', cat:'symbols', price:60, rarity:'epic'},
  {e:'⛔', name:'No Entry', cat:'symbols', price:10, rarity:'common'},
  {e:'📛', name:'Name Badge', cat:'symbols', price:10, rarity:'common'},
  {e:'🚫', name:'Prohibited Sign', cat:'symbols', price:10, rarity:'common'},
  {e:'💯', name:'100', cat:'symbols', price:25, rarity:'rare'},
  {e:'💢', name:'Anger', cat:'symbols', price:25, rarity:'rare'},
  {e:'♨️', name:'Hot Springs', cat:'symbols', price:10, rarity:'common'},
  {e:'🚷', name:'No Pedestrian', cat:'symbols', price:25, rarity:'rare'},
  {e:'🚯', name:'No Litter', cat:'symbols', price:10, rarity:'common'},
  {e:'🚳', name:'No Bikes', cat:'symbols', price:10, rarity:'common'},
  {e:'🚱', name:'Not Drinkable', cat:'symbols', price:10, rarity:'common'},
  {e:'🔞', name:'No 18', cat:'symbols', price:60, rarity:'epic'},
  {e:'📵', name:'No Phone', cat:'symbols', price:10, rarity:'common'},
  {e:'🚭', name:'No Smoke', cat:'symbols', price:25, rarity:'rare'},
  {e:'❗', name:'Exclamation', cat:'symbols', price:25, rarity:'rare'},
  {e:'❕', name:'Hollow Excl', cat:'symbols', price:25, rarity:'rare'},
  {e:'❓', name:'Question', cat:'symbols', price:10, rarity:'common'},
  {e:'❔', name:'Hollow Quest', cat:'symbols', price:25, rarity:'rare'},
  {e:'‼️', name:'Double Excl', cat:'symbols', price:10, rarity:'common'},
  {e:'⁉️', name:'Excl Quest', cat:'symbols', price:25, rarity:'rare'},
  {e:'🔅', name:'Dim', cat:'symbols', price:25, rarity:'rare'},
  {e:'🔆', name:'Bright', cat:'symbols', price:60, rarity:'epic'},
  {e:'〽️', name:'Part', cat:'symbols', price:25, rarity:'rare'},
  {e:'⚠️', name:'Warning', cat:'symbols', price:25, rarity:'rare'},
  {e:'🚸', name:'Crossing', cat:'symbols', price:10, rarity:'common'},
  {e:'🔱', name:'Trident', cat:'symbols', price:25, rarity:'rare'},
  {e:'⚜️', name:'Fleur', cat:'symbols', price:10, rarity:'common'},
  {e:'🔰', name:'Beginner', cat:'symbols', price:10, rarity:'common'},
  {e:'♻️', name:'Recycle', cat:'symbols', price:10, rarity:'common'},
  {e:'✅', name:'Check Mark', cat:'symbols', price:10, rarity:'common'},
  {e:'🈯', name:'Reserved', cat:'symbols', price:25, rarity:'rare'},
  {e:'💹', name:'Up Trend', cat:'symbols', price:10, rarity:'common'},
  {e:'❇️', name:'Spark', cat:'symbols', price:10, rarity:'common'},
  {e:'✳️', name:'Eight Spoke', cat:'symbols', price:25, rarity:'rare'},
  {e:'❎', name:'Cross Box', cat:'symbols', price:25, rarity:'rare'},
  {e:'🌐', name:'Globe Web', cat:'symbols', price:25, rarity:'rare'},
  {e:'💠', name:'Diamond Dot', cat:'symbols', price:10, rarity:'common'},
  {e:'Ⓜ️', name:'M', cat:'symbols', price:10, rarity:'common'},
  {e:'🌀', name:'Cyclone Sym', cat:'symbols', price:10, rarity:'common'},
  {e:'💤', name:'Zzz', cat:'symbols', price:60, rarity:'epic'},
  {e:'🏧', name:'ATM', cat:'symbols', price:10, rarity:'common'},
  {e:'🚾', name:'WC', cat:'symbols', price:10, rarity:'common'},
  {e:'♿', name:'Wheelchair', cat:'symbols', price:25, rarity:'rare'},
  {e:'🅿️', name:'P', cat:'symbols', price:25, rarity:'rare'},
  {e:'🛗', name:'Elevator', cat:'symbols', price:10, rarity:'common'},
  {e:'🈳', name:'Vacancy', cat:'symbols', price:25, rarity:'rare'},
  {e:'🈂️', name:'Service', cat:'symbols', price:10, rarity:'common'},
  {e:'🛂', name:'Passport', cat:'symbols', price:10, rarity:'common'},
  {e:'🛃', name:'Customs', cat:'symbols', price:60, rarity:'epic'},
  {e:'🛄', name:'Baggage', cat:'symbols', price:10, rarity:'common'},
  {e:'🛅', name:'Left Lug', cat:'symbols', price:10, rarity:'common'},
  {e:'🚹', name:'Men', cat:'symbols', price:60, rarity:'epic'},
  {e:'🚺', name:'Women', cat:'symbols', price:10, rarity:'common'},
  {e:'🚼', name:'Baby', cat:'symbols', price:10, rarity:'common'},
  {e:'🚻', name:'Restroom', cat:'symbols', price:10, rarity:'common'},
  {e:'🚮', name:'Litter', cat:'symbols', price:25, rarity:'rare'},
  {e:'🎦', name:'Cinema', cat:'symbols', price:10, rarity:'common'},
  {e:'📶', name:'Bars', cat:'symbols', price:10, rarity:'common'},
  {e:'🈁', name:'Here', cat:'symbols', price:10, rarity:'common'},
  {e:'🔣', name:'Symbols', cat:'symbols', price:10, rarity:'common'},
  {e:'ℹ️', name:'Info', cat:'symbols', price:10, rarity:'common'},
  {e:'🔤', name:'ABC', cat:'symbols', price:10, rarity:'common'},
  {e:'🔡', name:'abcd', cat:'symbols', price:10, rarity:'common'},
  {e:'🔠', name:'ABCD', cat:'symbols', price:10, rarity:'common'},
  {e:'🆖', name:'NG', cat:'symbols', price:10, rarity:'common'},
  {e:'🆗', name:'OK', cat:'symbols', price:10, rarity:'common'},
  {e:'🆙', name:'UP', cat:'symbols', price:10, rarity:'common'},
  {e:'🆒', name:'Cool', cat:'symbols', price:25, rarity:'rare'},
  {e:'🆕', name:'NEW', cat:'symbols', price:25, rarity:'rare'},
  {e:'🆓', name:'FREE', cat:'symbols', price:10, rarity:'common'},
  {e:'0️⃣', name:'0', cat:'symbols', price:60, rarity:'epic'},
  {e:'1️⃣', name:'1', cat:'symbols', price:10, rarity:'common'},
  {e:'2️⃣', name:'2', cat:'symbols', price:10, rarity:'common'},
  {e:'3️⃣', name:'3', cat:'symbols', price:25, rarity:'rare'},
  {e:'4️⃣', name:'4', cat:'symbols', price:25, rarity:'rare'},
  {e:'5️⃣', name:'5', cat:'symbols', price:10, rarity:'common'},
  {e:'6️⃣', name:'6', cat:'symbols', price:10, rarity:'common'},
  {e:'7️⃣', name:'7', cat:'symbols', price:10, rarity:'common'},
  {e:'8️⃣', name:'8', cat:'symbols', price:10, rarity:'common'},
  {e:'9️⃣', name:'9', cat:'symbols', price:25, rarity:'rare'},
  {e:'🔟', name:'10', cat:'symbols', price:25, rarity:'rare'},
  {e:'🔢', name:'1234', cat:'symbols', price:25, rarity:'rare'},
  {e:'#️⃣', name:'Hash', cat:'symbols', price:10, rarity:'common'},
  {e:'*️⃣', name:'Star Key', cat:'symbols', price:10, rarity:'common'},
  {e:'⏏️', name:'Eject', cat:'symbols', price:60, rarity:'epic'},
  {e:'▶️', name:'Play', cat:'symbols', price:25, rarity:'rare'},
  {e:'⏸️', name:'Pause', cat:'symbols', price:10, rarity:'common'},
  {e:'⏯️', name:'Play Pause', cat:'symbols', price:60, rarity:'epic'},
  {e:'⏹️', name:'Stop Btn', cat:'symbols', price:10, rarity:'common'},
  {e:'⏺️', name:'Record', cat:'symbols', price:10, rarity:'common'},
  {e:'⏭️', name:'Next Track', cat:'symbols', price:25, rarity:'rare'},
  {e:'⏮️', name:'Last Track', cat:'symbols', price:10, rarity:'common'},
  {e:'⏩', name:'Fast Fwd', cat:'symbols', price:10, rarity:'common'},
  {e:'⏪', name:'Rewind', cat:'symbols', price:10, rarity:'common'},
  {e:'⏫', name:'Double Up', cat:'symbols', price:25, rarity:'rare'},
  {e:'⏬', name:'Double Down', cat:'symbols', price:10, rarity:'common'},
  {e:'◀️', name:'Reverse', cat:'symbols', price:25, rarity:'rare'},
  {e:'🔼', name:'Up Btn', cat:'symbols', price:25, rarity:'rare'},
  {e:'🔽', name:'Down Btn', cat:'symbols', price:60, rarity:'epic'},
  {e:'➡️', name:'Right', cat:'symbols', price:150, rarity:'legendary'},
  {e:'⬅️', name:'Left', cat:'symbols', price:10, rarity:'common'},
  {e:'⬆️', name:'Up', cat:'symbols', price:10, rarity:'common'},
  {e:'⬇️', name:'Down', cat:'symbols', price:10, rarity:'common'},
  {e:'↗️', name:'Up Right', cat:'symbols', price:25, rarity:'rare'},
  {e:'↘️', name:'Down Right', cat:'symbols', price:10, rarity:'common'},
  {e:'↙️', name:'Down Left', cat:'symbols', price:150, rarity:'legendary'},
  {e:'↖️', name:'Up Left', cat:'symbols', price:10, rarity:'common'},
  {e:'↕️', name:'Up Down', cat:'symbols', price:10, rarity:'common'},
  {e:'↔️', name:'Left Right', cat:'symbols', price:10, rarity:'common'},
  {e:'↪️', name:'Right Hook', cat:'symbols', price:10, rarity:'common'},
  {e:'↩️', name:'Left Hook', cat:'symbols', price:10, rarity:'common'},
  {e:'⤴️', name:'Up Right Curve', cat:'symbols', price:60, rarity:'epic'},
  {e:'⤵️', name:'Down Right Curve', cat:'symbols', price:25, rarity:'rare'},
  {e:'🔀', name:'Shuffle', cat:'symbols', price:10, rarity:'common'},
  {e:'🔁', name:'Repeat', cat:'symbols', price:25, rarity:'rare'},
  {e:'🔂', name:'Repeat One', cat:'symbols', price:10, rarity:'common'},
  {e:'🔄', name:'Counter Clock', cat:'symbols', price:10, rarity:'common'},
  {e:'🔃', name:'Clockwise', cat:'symbols', price:60, rarity:'epic'},
  {e:'🎵', name:'Note', cat:'symbols', price:10, rarity:'common'},
  {e:'🎶', name:'Notes', cat:'symbols', price:10, rarity:'common'},
  {e:'➕', name:'Plus', cat:'symbols', price:10, rarity:'common'},
  {e:'➖', name:'Minus', cat:'symbols', price:10, rarity:'common'},
  {e:'➗', name:'Divide', cat:'symbols', price:10, rarity:'common'},
  {e:'✖️', name:'Multiply', cat:'symbols', price:10, rarity:'common'},
  {e:'🟰', name:'Equals', cat:'symbols', price:25, rarity:'rare'},
  {e:'♾️', name:'Infinity', cat:'symbols', price:10, rarity:'common'},
  {e:'💲', name:'Heavy Dollar', cat:'symbols', price:10, rarity:'common'},
  {e:'💱', name:'Currency', cat:'symbols', price:10, rarity:'common'},
  {e:'™️', name:'TM', cat:'symbols', price:10, rarity:'common'},
  {e:'©️', name:'Copyright', cat:'symbols', price:10, rarity:'common'},
  {e:'®️', name:'Registered', cat:'symbols', price:10, rarity:'common'},
  {e:'〰️', name:'Wavy', cat:'symbols', price:10, rarity:'common'},
  {e:'➰', name:'Curly Loop', cat:'symbols', price:25, rarity:'rare'},
  {e:'➿', name:'Double Loop', cat:'symbols', price:25, rarity:'rare'},
  {e:'🔚', name:'End', cat:'symbols', price:25, rarity:'rare'},
  {e:'🔙', name:'Back', cat:'symbols', price:10, rarity:'common'},
  {e:'🔛', name:'On', cat:'symbols', price:10, rarity:'common'},
  {e:'🔝', name:'Top', cat:'symbols', price:60, rarity:'epic'},
  {e:'🔜', name:'Soon', cat:'symbols', price:10, rarity:'common'},
  {e:'✔️', name:'Heavy Check', cat:'symbols', price:10, rarity:'common'},
  {e:'☑️', name:'Ballot Check', cat:'symbols', price:10, rarity:'common'},
  {e:'🔘', name:'Radio', cat:'symbols', price:10, rarity:'common'},
  {e:'🔴', name:'Red Circle', cat:'symbols', price:10, rarity:'common'},
  {e:'🟠', name:'Orange Circle', cat:'symbols', price:25, rarity:'rare'},
  {e:'🟡', name:'Yellow Circle', cat:'symbols', price:10, rarity:'common'},
  {e:'🟢', name:'Green Circle', cat:'symbols', price:10, rarity:'common'},
  {e:'🔵', name:'Blue Circle', cat:'symbols', price:10, rarity:'common'},
  {e:'🟣', name:'Purple Circle', cat:'symbols', price:25, rarity:'rare'},
  {e:'⚫', name:'Black Circle', cat:'symbols', price:150, rarity:'legendary'},
  {e:'⚪', name:'White Circle', cat:'symbols', price:150, rarity:'legendary'},
  {e:'🟤', name:'Brown Circle', cat:'symbols', price:10, rarity:'common'},
  {e:'🟥', name:'Red Square', cat:'symbols', price:10, rarity:'common'},
  {e:'🟧', name:'Orange Square', cat:'symbols', price:10, rarity:'common'},
  {e:'🟨', name:'Yellow Square', cat:'symbols', price:10, rarity:'common'},
  {e:'🟩', name:'Green Square', cat:'symbols', price:10, rarity:'common'},
  {e:'🟦', name:'Blue Square', cat:'symbols', price:25, rarity:'rare'},
  {e:'🟪', name:'Purple Square', cat:'symbols', price:10, rarity:'common'},
  {e:'⬛', name:'Black Square', cat:'symbols', price:60, rarity:'epic'},
  {e:'⬜', name:'White Square', cat:'symbols', price:10, rarity:'common'},
  {e:'🟫', name:'Brown Square', cat:'symbols', price:10, rarity:'common'},
  {e:'◼️', name:'Med Black', cat:'symbols', price:10, rarity:'common'},
  {e:'◻️', name:'Med White', cat:'symbols', price:60, rarity:'epic'},
  {e:'◾', name:'Sm Black', cat:'symbols', price:10, rarity:'common'},
  {e:'◽', name:'Sm White', cat:'symbols', price:60, rarity:'epic'},
  {e:'▪️', name:'XSm Black', cat:'symbols', price:10, rarity:'common'},
  {e:'▫️', name:'XSm White', cat:'symbols', price:25, rarity:'rare'},
  {e:'🔺', name:'Up Triangle', cat:'symbols', price:25, rarity:'rare'},
  {e:'🔻', name:'Down Triangle', cat:'symbols', price:10, rarity:'common'},
  {e:'🔸', name:'Sm Diamond', cat:'symbols', price:25, rarity:'rare'},
  {e:'🔹', name:'Sm Blue Diamond', cat:'symbols', price:10, rarity:'common'},
  {e:'🔶', name:'Diamond', cat:'symbols', price:10, rarity:'common'},
  {e:'🔷', name:'Blue Diamond', cat:'symbols', price:10, rarity:'common'},
  {e:'🔳', name:'White Square Btn', cat:'symbols', price:150, rarity:'legendary'},
  {e:'🔲', name:'Black Square Btn', cat:'symbols', price:10, rarity:'common'},
  {e:'🌱', name:'Seedling', cat:'plants', price:10, rarity:'common'},
  {e:'🪴', name:'Potted', cat:'plants', price:10, rarity:'common'},
  {e:'🌲', name:'Evergreen', cat:'plants', price:10, rarity:'common'},
  {e:'🌳', name:'Tree', cat:'plants', price:10, rarity:'common'},
  {e:'🌴', name:'Palm', cat:'plants', price:10, rarity:'common'},
  {e:'🌵', name:'Cactus', cat:'plants', price:60, rarity:'epic'},
  {e:'🌾', name:'Sheaf', cat:'plants', price:10, rarity:'common'},
  {e:'🌿', name:'Herb', cat:'plants', price:25, rarity:'rare'},
  {e:'☘️', name:'Shamrock', cat:'plants', price:150, rarity:'legendary'},
  {e:'🍀', name:'Four Leaf', cat:'plants', price:10, rarity:'common'},
  {e:'🍁', name:'Maple', cat:'plants', price:10, rarity:'common'},
  {e:'🍂', name:'Fallen', cat:'plants', price:10, rarity:'common'},
  {e:'🍃', name:'Wind Leaf', cat:'plants', price:10, rarity:'common'},
  {e:'🪺', name:'Nest Eggs', cat:'plants', price:60, rarity:'epic'},
  {e:'🪹', name:'Nest Empty', cat:'plants', price:150, rarity:'legendary'},
  {e:'🌷', name:'Tulip', cat:'plants', price:10, rarity:'common'},
  {e:'🌹', name:'Rose', cat:'plants', price:25, rarity:'rare'},
  {e:'🥀', name:'Wilted', cat:'plants', price:10, rarity:'common'},
  {e:'🌺', name:'Hibiscus', cat:'plants', price:10, rarity:'common'},
  {e:'🌸', name:'Cherry Blossom', cat:'plants', price:10, rarity:'common'},
  {e:'🌼', name:'Blossom', cat:'plants', price:25, rarity:'rare'},
  {e:'🌻', name:'Sunflower', cat:'plants', price:25, rarity:'rare'},
  {e:'🪷', name:'Lotus', cat:'plants', price:10, rarity:'common'},
  {e:'🪻', name:'Hyacinth', cat:'plants', price:10, rarity:'common'},
  {e:'👋', name:'Wave', cat:'hands', price:60, rarity:'epic'},
  {e:'🤚', name:'Raised Back', cat:'hands', price:25, rarity:'rare'},
  {e:'🖐️', name:'Raised', cat:'hands', price:10, rarity:'common'},
  {e:'✋', name:'Raised Open', cat:'hands', price:25, rarity:'rare'},
  {e:'🖖', name:'Vulcan', cat:'hands', price:10, rarity:'common'},
  {e:'👌', name:'OK', cat:'hands', price:25, rarity:'rare'},
  {e:'🤌', name:'Pinched', cat:'hands', price:25, rarity:'rare'},
  {e:'🤏', name:'Pinch', cat:'hands', price:10, rarity:'common'},
  {e:'✌️', name:'Victory', cat:'hands', price:10, rarity:'common'},
  {e:'🤞', name:'Crossed', cat:'hands', price:25, rarity:'rare'},
  {e:'🫰', name:'Heart Hand', cat:'hands', price:25, rarity:'rare'},
  {e:'🤟', name:'Love You', cat:'hands', price:10, rarity:'common'},
  {e:'🤘', name:'Rock On', cat:'hands', price:10, rarity:'common'},
  {e:'🤙', name:'Call Me', cat:'hands', price:25, rarity:'rare'},
  {e:'👈', name:'Point Left', cat:'hands', price:10, rarity:'common'},
  {e:'👉', name:'Point Right', cat:'hands', price:10, rarity:'common'},
  {e:'👆', name:'Point Up', cat:'hands', price:10, rarity:'common'},
  {e:'🖕', name:'Mid Finger', cat:'hands', price:10, rarity:'common'},
  {e:'👇', name:'Point Down', cat:'hands', price:10, rarity:'common'},
  {e:'☝️', name:'Index Up', cat:'hands', price:10, rarity:'common'},
  {e:'🫵', name:'Pointing You', cat:'hands', price:10, rarity:'common'},
  {e:'👍', name:'Thumbs Up', cat:'hands', price:25, rarity:'rare'},
  {e:'👎', name:'Thumbs Down', cat:'hands', price:10, rarity:'common'},
  {e:'✊', name:'Fist', cat:'hands', price:10, rarity:'common'},
  {e:'👊', name:'Fist Bump', cat:'hands', price:10, rarity:'common'},
  {e:'🤛', name:'Left Fist', cat:'hands', price:10, rarity:'common'},
  {e:'🤜', name:'Right Fist', cat:'hands', price:60, rarity:'epic'},
  {e:'👏', name:'Clap', cat:'hands', price:25, rarity:'rare'},
  {e:'🙌', name:'Raised Hands', cat:'hands', price:10, rarity:'common'},
  {e:'🫶', name:'Heart Hands', cat:'hands', price:25, rarity:'rare'},
  {e:'👐', name:'Open Hands', cat:'hands', price:60, rarity:'epic'},
  {e:'🤲', name:'Palms Up', cat:'hands', price:25, rarity:'rare'},
  {e:'🤝', name:'Handshake', cat:'hands', price:25, rarity:'rare'},
  {e:'🙏', name:'Pray', cat:'hands', price:10, rarity:'common'},
  {e:'✍️', name:'Writing', cat:'hands', price:10, rarity:'common'},
  {e:'💅', name:'Nail Polish', cat:'hands', price:25, rarity:'rare'},
  {e:'🤳', name:'Selfie', cat:'hands', price:25, rarity:'rare'},
  {e:'💪', name:'Bicep', cat:'hands', price:25, rarity:'rare'},
  {e:'🦾', name:'Robot Arm', cat:'hands', price:10, rarity:'common'},
  {e:'🦿', name:'Robot Leg', cat:'hands', price:10, rarity:'common'},
  {e:'🦵', name:'Leg', cat:'hands', price:10, rarity:'common'},
  {e:'🦶', name:'Foot', cat:'hands', price:10, rarity:'common'},
  {e:'👂', name:'Ear', cat:'hands', price:10, rarity:'common'},
  {e:'🦻', name:'Ear Hearing Aid', cat:'hands', price:10, rarity:'common'},
  {e:'👃', name:'Nose', cat:'hands', price:10, rarity:'common'},
  {e:'🧠', name:'Brain', cat:'hands', price:25, rarity:'rare'},
  {e:'🫀', name:'Anatomical Heart', cat:'hands', price:10, rarity:'common'},
  {e:'🫁', name:'Lungs', cat:'hands', price:25, rarity:'rare'},
  {e:'🦷', name:'Tooth', cat:'hands', price:10, rarity:'common'},
  {e:'🦴', name:'Bone Hand', cat:'hands', price:150, rarity:'legendary'},
  {e:'👀', name:'Eyes', cat:'hands', price:10, rarity:'common'},
  {e:'👁️', name:'Eye', cat:'hands', price:10, rarity:'common'},
  {e:'👅', name:'Tongue Body', cat:'hands', price:10, rarity:'common'},
  {e:'👄', name:'Mouth', cat:'hands', price:25, rarity:'rare'},
  {e:'🫦', name:'Biting Lip', cat:'hands', price:10, rarity:'common'},
];
// Total: 1112 emojis